#!/bin/bash

# Copyright (c) 2020, Zoltán Rési
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function prompt_overwrite() {
	read -r -p "File $1 already exists. Would you like to overwrite it? [Y/n]" input
	while true; do
		case $input in
			[Yy]* ) echo "yes"; break;;
			[Nn]* ) echo "no"; break;;
			* ) echo "Please answer Y(es) or N(o).";;
		esac
	done
}


if [ -f .travis.yml ]; then
	local overwrite=$(prompt_overwrite ".travis.yml")
	if [ $overwrite == "yes" ]; then
		rm -f .travis.yml
	else
		echo "Skipped file .travis.yml."
		return
	fi
fi
echo "# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

language: cpp # optional, just removes the language badge
compiler:
  - gcc
os:
  - linux
branches:
  only:
  - master

# include the following block if the C/C++ build artifacts should get cached by Travis,
# CCACHE_DIR needs to get set as well to actually fill the cache
#cache:
#  directories:
#    - \$HOME/.ccache

git:
  quiet: true # optional, silences the cloning of the target repository

# configure the build environment(s)
# https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#variables-you-can-configure
env:
  global: # global settings for all jobs
    - ROS_REPO=ros
    - CCACHE_DIR=\$HOME/.ccache # enables C/C++ caching in industrial_ci
    - BUILDER='colcon'
    - SONARQUBE='true'
    - TEST_COVERAGE='true'
  matrix: # each line is a job
    - ROS_DISTRO='dashing'

notifications:
  email: false

# clone and run industrial_ci
install:
  - git clone --quiet --depth 1 https://github.com/kroshu/industrial_ci.git .industrial_ci
  - curl \"https://raw.githubusercontent.com/davetcoleman/roscpp_code_format/master/.clang-format\" -o .clang-format
script:
- .industrial_ci/travis.sh" >> .travis.yml

if [ "$EUID" -eq 0 ]; then
	chown $SUDO_USER .travis.yml
fi
echo "Added file .travis.yml."

